<?php

/**
 * Enqueue Script
 *
 * This class is responsible for registering and enqueuing scripts.
 *
 * This class internally uses asset information to set script dependencies,
 * and version generated by @wordpress/dependency-extraction-webpack-plugin package.
 * It also handles script translation registration.
 *
 * @package WpRollback\Core
 * @unreleased
 */

declare(strict_types=1);

namespace WpRollback\Core;

use InvalidArgumentException;

use function wp_set_script_translations;

/**
 * Class EnqueueScript
 *
 * @unreleased
 */
class EnqueueScript
{
    /**
     * @unreleased
     *
     * @var string Script id.
     */
    private $scriptId;

    /**
     * @unreleased
     *
     * @var string Relative script path.
     */
    private $relativeScriptPath;

    /**
     * @unreleased
     *
     * @var string
     */
    private $absoluteScriptPath;

    /**
     * @unreleased
     *
     * @var array Array of script dependencies.
     */
    private $scriptDependencies = [];

    /**
     * @unreleased
     *
     * @var bool A flag to tell whether to load script in footer.
     */
    private $loadScriptInFooter = false;

    /**
     * @unreleased
     *
     * @var bool A flag to tell whether to register translations for a script.
     */
    private $registerTranslations = false;

    /**
     * @unreleased
     *
     * @var string Localize script param name.
     */
    private $localizeScriptParamName;

    /**
     * @unreleased
     *
     * @var mixed Localize script data.
     */
    private $localizeScriptParamData;

    /**
     * @unreleased
     *
     * @var string Plugin directory path.
     */
    private $pluginDirPath;

    /**
     * @unreleased
     *
     * @var string Plugin directory url.
     */
    private $pluginDirUrl;

    /**
     * @unreleased
     *
     * @var string  Text domain.
     */
    private $textDomain;

    /**
     * @unreleased
     *
     * @var string Original script id.
     */
    private $originalScriptId;

    /**
     * @unreleased
     *
     * @var bool A flag to tell whether to load style.
     */
    private $loadStyle = false;

    /**
     * @unreleased
     *
     * @var array Array of style dependencies.
     */
    private array $styleDependencies;

    /**
     * Constructor.
     *
     * @unreleased
     */
    public function __construct(string $scriptId, string $scriptPath)
    {
        $scriptPrefix = Constants::PLUGIN_SLUG;
        $this->pluginDirPath = Constants::$PLUGIN_DIR;
        $this->pluginDirUrl = Constants::$PLUGIN_URL;
        $this->textDomain = 'stellarpay';
        $this->originalScriptId = $scriptId;
        $this->scriptId = "$scriptPrefix-$scriptId-js";
        $this->relativeScriptPath = $scriptPath;
        $this->absoluteScriptPath = $this->pluginDirPath . $this->relativeScriptPath;

        if (empty($scriptId)) {
            throw new InvalidArgumentException('Script id cannot be empty');
        }

        if (!file_exists($this->absoluteScriptPath)) {
            throw new InvalidArgumentException("Invalid script path provided: $scriptPath"); // phpcs:ignore
        }
    }

    /**
     * This function sets a flag to load script in footer.
     *
     * @unreleased
     *
     * @return $this
     */
    public function loadInFooter(): EnqueueScript
    {
        $this->loadScriptInFooter = true;

        return $this;
    }

    /**
     * This function sets a flag to load style with script.
     *
     * The WordPress dependency extraction javascript package generate a style file which we can load with script.
     *
     * @unreleased
     *
     * @return $this
     */
    public function loadStyle(array $dependencies = []): EnqueueScript
    {
        $this->loadStyle = true;
        $this->styleDependencies = $dependencies;

        return $this;
    }

    /**
     * This function sets additional script dependencies.
     *
     * These additional dependencies adds to list of dependencies
     * generates by WordPress dependency extraction javascript package.
     *
     * @unreleased
     *
     * @param array $scriptDependencies
     *
     * @return $this
     */
    public function dependencies(array $scriptDependencies): EnqueueScript
    {
        $this->scriptDependencies = $scriptDependencies;

        return $this;
    }

    /**
     * @unreleased
     */
    public function register(): EnqueueScript
    {
        $scriptUrl = $this->pluginDirUrl . $this->relativeScriptPath;
        $scriptAsset = $this->getAssetFileData();

        wp_register_script(
            $this->scriptId,
            $scriptUrl,
            $scriptAsset['dependencies'],
            $scriptAsset['version'],
            $this->loadScriptInFooter
        );

        if ($this->registerTranslations) {
            wp_set_script_translations(
                $this->scriptId,
                $this->textDomain,
                $this->pluginDirPath . 'languages'
            );
        }

        if ($this->localizeScriptParamData) {
            wp_localize_script(
                $this->scriptId,
                $this->localizeScriptParamName,
                $this->localizeScriptParamData
            );
        }

        return $this;
    }

    /**
     * This function sets a flag to enable registration of translations for a script.
     *
     * @unreleased
     * @return $this
     */
    public function registerTranslations(): EnqueueScript
    {
        $this->registerTranslations = true;

        return $this;
    }

    /**
     * This function sets localize data for a script which output when script enqueue.
     *
     * @unreleased
     */
    public function registerLocalizeData(string $jsVariableName, array $data): EnqueueScript
    {
        $this->localizeScriptParamName = $jsVariableName;
        $this->localizeScriptParamData = $data;

        return $this;
    }

    /**
     * This function enqueues a script.
     *
     * @unreleased
     */
    public function enqueue(): EnqueueScript
    {
        if (!wp_script_is($this->scriptId, 'registered')) {
            $this->register();
        }

        wp_enqueue_script($this->scriptId);
        $this->enqueueStyle();

        return $this;
    }

    /**
     * This function enqueues a style if "loadStyle" flag is set to true.
     *
     * @unreleased
     */
    protected function enqueueStyle(): void
    {
        if (!$this->loadStyle) {
            return;
        }

        $relativePath = str_replace('.js', '.css', $this->relativeScriptPath);

        wp_enqueue_style(
            "$this->originalScriptId-css",
            $this->pluginDirUrl . $relativePath,
            $this->styleDependencies,
            $this->getVersion()
        );
    }

    /**
     * This function returns script id.
     *
     * @unreleased
     */
    public function getScriptId(): string
    {
        return $this->scriptId;
    }

    /**
     * This function returns script data.
     *
     * The Script data generates by WordPress dependency extraction javascript package.
     *
     * @unreleased
     */
    public function getAssetFileData(): array
    {
        $scriptAssetPath = trailingslashit(dirname($this->absoluteScriptPath))
            . basename($this->absoluteScriptPath, '.js')
            . '.asset.php';

        if (!file_exists($scriptAssetPath)) {
            // phpcs:ignore
            throw new InvalidArgumentException("Asset file not found for script: $this->absoluteScriptPath");
        }

        $scriptAsset = require($scriptAssetPath);

        if ($this->scriptDependencies) {
            $scriptAsset['dependencies'] = array_merge($this->scriptDependencies, $scriptAsset['dependencies']);
        }

        return $scriptAsset;
    }

    /**
     * This function returns script version.
     *
     * The script version generates by WordPress dependency extraction javascript package.
     *
     * @unreleased
     *
     * @return string
     */
    public function getVersion(): string
    {
        return $this->getAssetFileData()['version'];
    }
}
